#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

# E V E N T S
sketchybar -m --add event window_focus \
              --add event title_change

FONT="SF Pro"
PADDINGS=3 # All paddings use this value (icon, label, background)

bar=(
    height=25
    color=$BAR_COLOR
    shadow=off
    position=top
    sticky=off
    padding_right=10
    padding_left=10
    margin=-2
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####

defaults=(
    #updates=when_shown
    icon.font="Hack Nerd Font:Bold:16.0"
    icon.color=$ICON_COLOR
    icon.padding_left=$PADDINGS
    icon.padding_right=$PADDINGS
    label.font="MxPlus ToshibaSat 8x14:monospace:15.0"
    label.color=$LABEL_COLOR
    padding_left=$PADDINGS
    padding_right=$PADDINGS
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
)

sketchybar --default "${defaults[@]}"

# sketchybar --default icon.font="Hack Nerd Font:Bold:16.0"  \
#                      icon.color=$ICON_COLOR                 \
#                      label.font="MxPlus ToshibaSat 8x14:monospace:15.0" \
#                      label.color=$LABEL_COLOR                \
#                      padding_left=3                        \
#                      padding_right=3                       \
#                      label.padding_left=3                  \
#                      label.padding_right=3                 \
#                      icon.padding_left=3                  \
#                      icon.padding_right=3

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

# for i in "${!SPACE_ICONS[@]}"
# do
#   sid=$(($i+1))
#   sketchybar --add space space.$sid left                                 \
#              --set space.$sid associated_space=$sid                      \
#                               icon.string=""                                     \
#                               icon.y_offset=1                              \
#                               icon.font="Hack Nerd Font:Bold:25.4"    \
#                               icon.color=0xd9D3A273                      \
#                               label.font="Hack Nerd Font:Bold:27.4"   \
#                               label.string=""                              \
#                               label.color=0xd9D3A273    \
#                               label.y_offset=1.9      \
#                               label.padding_left=-23  \
#                               label.padding_right=-3 \
#                               label.drawing=off                          \
#                               script="$PLUGIN_DIR/space.sh"              \
#                               click_script="yabai -m space --focus $sid"
# done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

# source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/yabai.sh"
sketchybar --add item space_separator left              \
           --set space_separator padding_left=-1        \
                                label.drawing=off       \
           --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched


# W I N D O W  T I T L E 
sketchybar --add item title left \
              --set title       script="$PLUGIN_DIR/window_title.sh" \
              --subscribe title window_focus front_app_switched space_change title_change

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item wifi right                               \
           --set wifi    script="$PLUGIN_DIR/wifi.sh"          \
                         icon.drawing=off                    \
           --subscribe wifi wifi_change                        \
           --add item battery right                            \
           --set battery script="$PLUGIN_DIR/battery.sh"       \
                         icon.color=0xff8fc8BB                 \
                         update_freq=120                       \
           --subscribe battery system_woke power_source_change \
                                                                \
            --add item clock right                              \
           --set clock  icon.font="MxPlus ToshibaSat 8x14:Regular:15.0"\
                        　label.font="MxPlus ToshibaSat 8x14:Regular:15.0"\
                         update_freq=30                        \
                         icon=                                \
                         script="$PLUGIN_DIR/clock.sh"         \
                                                               \
           --add item sound right                             \
           --set sound  update_freq=120                       \
                        script="bash $PLUGIN_DIR/sound.sh"        


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
